cardiologytrials.org/django_cardiologytrials/django_cardiologytrials/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse
from trialsapp.sitemap import *
from trialsapp.feeds import LatestTrialsFeed
from trialsapp.feeds import AllTrialsFeed
admin.autodiscover()

# a dictionary of sitemaps
sitemaps = {
	'main': MainSitemap,
    'trials': TrialSitemap,
	'acs': ACSSitemap,
	'af': AFSitemap,
	'cad': CADSitemap,
	'hf': HFSitemap,
	'htn': HTNSitemap,
	'intervention': InterventionSitemap,
	'lipids': LipidsSitemap,
	'surgery': SurgerySitemap,	
}

urlpatterns = patterns('',
	
	url(r'^admin/', include(admin.site.urls)),
	
	(r'^$', 'trialsapp.views.index'),
	
	(r'^detail/(?P<trial_id>\d+)/$', 'trialsapp.views.detail'),
	
	(r'^short/(?P<trial_id>\d+)/$', 'trialsapp.views.short'),
	
	(r'^acs/', 'trialsapp.views.acs'),
	(r'^af/', 'trialsapp.views.af'),
	(r'^cad/', 'trialsapp.views.cad'),
	(r'^hf/', 'trialsapp.views.hf'),
	(r'^htn/', 'trialsapp.views.htn'),
	(r'^intervention/', 'trialsapp.views.intervention'),
	(r'^lipids/', 'trialsapp.views.lipids'),
	(r'^surgery/', 'trialsapp.views.surgery'),
	
	(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nAllow: /", mimetype="text/plain")),
	
	(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
	
	(r'^feeds/latest/rss\.xml$', LatestTrialsFeed()),
	
	(r'^feeds/all/rss\.xml$', AllTrialsFeed()),
	
	#(r'^newdesign/', 'trialsapp.views.newdesign'),

)

cardiologytrials.org/django_cardiologytrials/trialsapp/models.py
from django.db import models
from datetime import datetime

# Create your models here.
	
class Topic(models.Model):							# left-most column in the table
	name = models.CharField(max_length=200)
	displayname = models.CharField(max_length=200)
	def __unicode__(self):
		return self.name
		
class Therapy(models.Model):						# 2nd column in the table
	name = models.CharField(max_length=200)
	displayname = models.CharField(max_length=200)
	topic = models.ForeignKey(Topic)
	def __unicode__(self):
		return self.topic.name + " / " + self.name

class Intervention(models.Model):					# 3rd column in the table
	name = models.CharField(max_length=200)
	displayname = models.CharField(max_length=200)
	therapy = models.ForeignKey(Therapy)
	def __unicode__(self):
		return self.therapy.__unicode__() + " / " + self.name

class Trial(models.Model):
	name = models.CharField(max_length=200)
	date = models.DateField()
	pub_date = models.DateTimeField(default=datetime.now, blank=True)
	problem = models.CharField(max_length=200)
	format = models.CharField(max_length=200,default='-')
	population = models.CharField(max_length=200)
	inclusion = models.TextField()
	exclusion = models.TextField()
	treatment = models.CharField(max_length=200)
	control = models.CharField(max_length=200)
	followup = models.CharField(max_length=200)
	primary_endpoint = models.TextField()
	secondary_endpoint = models.TextField()
	details = models.TextField(blank=True)
	brief_summary = models.CharField(max_length=200,blank=True)
	topic_therapy_intervention = models.ManyToManyField(Intervention)
	def __unicode__(self):
		return self.name
	def get_absolute_url(self):
		return "/detail/%i/" % self.id

class Paper(models.Model):
	trial = models.ForeignKey(Trial)
	name = models.CharField(max_length=200)
	date = models.DateField()
	journal = models.CharField(max_length=200)
	pmid = models.CharField(max_length=200)
	benefit = models.IntegerField()
	benefit_details = models.TextField()
	def __unicode__(self):
		return self.journal

cardiologytrials.org/django_cardiologytrials/trialsapp/views.py
from django.shortcuts import render_to_response, get_object_or_404
from trialsapp.models import Trial,Topic
from django.template import RequestContext

def index(request):
	topics_list=Topic.objects.order_by('name')
	return render_to_response('trialsapp/cardio.html', {'topics_list':topics_list},context_instance=RequestContext(request))

def detail(request, trial_id):
	p = get_object_or_404(Trial, pk=trial_id)
	return render_to_response('trialsapp/detail.html', {'trial': p}, context_instance=RequestContext(request))
	
def short(request, trial_id):
	p = get_object_or_404(Trial, pk=trial_id)
	return render_to_response('trialsapp/short.html', {'trial': p}, context_instance=RequestContext(request))
	
def acs(request):
	topics_list=Topic.objects.filter(name='ACS')
	return render_to_response('trialsapp/acs.html', {'topics_list':topics_list},context_instance=RequestContext(request))
	
def af(request):
	topics_list=Topic.objects.filter(name='AF')
	return render_to_response('trialsapp/af.html', {'topics_list':topics_list},context_instance=RequestContext(request))
	
def cad(request):
	topics_list=Topic.objects.filter(name='CAD')
	return render_to_response('trialsapp/cad.html', {'topics_list':topics_list},context_instance=RequestContext(request))
	
def hf(request):
	topics_list=Topic.objects.filter(name='HF')
	return render_to_response('trialsapp/hf.html', {'topics_list':topics_list},context_instance=RequestContext(request))
	
def htn(request):
	topics_list=Topic.objects.filter(name='HTN')
	return render_to_response('trialsapp/htn.html', {'topics_list':topics_list},context_instance=RequestContext(request))
	
def intervention(request):
	topics_list=Topic.objects.filter(name='Intervention')
	return render_to_response('trialsapp/intervention.html', {'topics_list':topics_list},context_instance=RequestContext(request))
	
def lipids(request):
	topics_list=Topic.objects.filter(name='Lipids')
	return render_to_response('trialsapp/lipids.html', {'topics_list':topics_list},context_instance=RequestContext(request))
	
def surgery(request):
	topics_list=Topic.objects.filter(name='Surgery')
	return render_to_response('trialsapp/surgery.html', {'topics_list':topics_list},context_instance=RequestContext(request))

cardiologytrials.org/django_cardiologytrials/templates/trialsapp/acs.html
{% extends "trialsapp/base.html" %}

{% block title %}Acute coronary syndrome (ACS) trials - CardiologyTrials.org{% endblock %}

{% block content %}
{% load trialsapp_extras %}
<div id="container">	
	<table class="trialtable">
		<tr>
			<th colspan="4"><h1>Evidence for acute coronary syndrome (ACS) therapies</h1></th>
		</tr>
		<tr>
			<td colspan="4">
			<p><red>Antiplatelet therapy</red> is the mainstay of treatment; aspirin (<a href="/detail/22/" rel="/short/22/">ISIS-2</a>) and clopidogrel (<a href="/detail/29/" rel="/short/29/">CURE</a>, <a href="/detail/78/" rel="/short/78/">COMMIT</a>) improve mortality. Newer P2Y12 inhibitors improve mortality further (<a href="/detail/28/" rel="/short/28/">TRITON-TIMI-38</a>, <a href="/detail/27/" rel="/short/27/">PLATO</a>), but possibly not those conservatively managed (<a href="/detail/92/" rel="/short/92/">TRILOGY-ACS</a>). GPIIbIIIa inhibitors have also shown benefit (<a href="/detail/66/" rel="/short/66/">CADILLAC</a>) but are not typically used with bivalirudin (<a href="/detail/65/" rel="/short/65/">HORIZONS-AMI</a>)</p><br />
			<p><red>Anti-thrombotic therapy</red> is beneficial and Fondaparinux is as effective as Enoxaparin but safer (<a href="/detail/52/" rel="/short/52/">OASIS-5</a>). UFH is only necessary in PCI (<a href="/detail/23/" rel="/short/23/">ISIS-3</a>, <a href="/detail/53/" rel="/short/53/">OASIS-6</a>), but is still beneficial alongside fondaparinux (<a href="/detail/53/" rel="/short/53/">OASIS-6</a>). Bivaliruin does not need UFH/GPIIbIIIa cover and is safer (<a href="/detail/65/" rel="/short/65/">HORIZONS-AMI</a>).</p><br />
			<p><red>Beta-blockers</red> improve mortality (<a href="/detail/21/" rel="/short/21/">ISIS-1</a>) but caution is needed in first 24 hours (<a href="/detail/78/" rel="/short/78/">COMMIT</a>).</p><br />
			<p><red>ACE inhibitors</red> improve mortality after ACS (<a href="/detail/24/" rel="/short/24/">ISIS-4</a>, <a href="/detail/83/" rel="/short/83/">GISSI-3</a>), and <red>Aldosterone antagonists</red> are beneficial where LVF/CCF is present (<a href="/detail/55/" rel="/short/55/">EPHESUS</a>).</p><br />
			<p><red>PCI</red> for STEMI is superior to thrombolysis, even when performed routinely after thrombolysis (<a href="/detail/62/" rel="/short/62/">NORDISTEMI</a>). PCI is also beneficial in NSTEMI patients (<a href="/detail/70/" rel="/short/70/">TACTICS-TIMI-18</a>, <a href="/detail/75/" rel="/short/75/">RITA-3</a>).</p><br />
			<p><red>Statins</red> reduce recurrent cardiovascular events, with a trend emerging as early as 30 days (<a href="/detail/61/" rel="/short/61/">PROVE-IT</a>). Other secondary prevention medications include Rivaroxaban (<a href="/detail/40/" rel="/short/40/">ATLAS-ACS-2-TIMI-51</a>)
			</td>
		</tr>
		<tr>
			<th>Topic</th>
			<th>Therapy group</th>
			<th>Therapy</th>
			<th>Trial</th>
		</tr>
		<tr>
		{% for topic in topics_list|dictsort:"name" %}
			<td colspan="1" rowspan="{% get_topic_rows topic %}"><a href="#" name="{{ topic }}">{{ topic.displayname }}</a></td>
			{% for therapy in topic.therapy_set.all|dictsort:"name" %}
				<td colspan="1" rowspan="{% get_therapy_rows therapy %}">{{ therapy.displayname }}</td>
				{% for intervention in therapy.intervention_set.all|dictsort:"name" %}
				<td>{{intervention.displayname }}</td>
					<td>{% for trial in intervention.trial_set.all|dictsort:"date" %}
						<a href="/detail/{{ trial.id }}/" rel="/short/{{ trial.id }}/">{{ trial }}{% if not forloop.last %},{% endif %}</a>{% endfor %}
					</td>
		</tr>
				{% endfor %}
			{% endfor %}
		{% endfor %}
	</table>
		
</div>
{% endblock %}

cardiologytrials.org/django_cardiologytrials/templates/trialsapp/af.html
{% extends "trialsapp/base.html" %}

{% block title %}Atrial fibrillation (AF) trials - CardiologyTrials.org{% endblock %}

{% block content %}
{% load trialsapp_extras %}
<div id="container">	
	<table class="trialtable">
		<tr>
			<th colspan="4"><h1>Evidence for atrial fibrillation (AF) therapies</h1></th>
		</tr>
		<tr>
			<td colspan="4">
			<p><red>Rate control</red> is non-inferior to <red>rhythm control</red> and may be superior in elderly or co-morbid patients (<a href="/detail/31/" rel="/short/31/">AFFIRM</a>). Strict rate control may provide no further benefits (<a href="/detail/76/" rel="/short/76/">RACE-II</a>)</p><br />
			<p><red>Anticoagulation</red> is beneficial even in rhythm control (<a href="/detail/31/" rel="/short/31/">AFFIRM</a>). Aspirin is sufficient in low-risk patients (<a href="/detail/49/" rel="/short/49/">SPAF</a>), but anti-thrombotic agents are necessary in high risk patients (<a href="/detail/50/" rel="/short/50/">SPAF-II</a>). Newer agents such as apixiban (<a href="/detail/42/" rel="/short/42/">ARISTOTLE</a>), rivaroxaban (<a href="/detail/43/" rel="/short/43/">ROCKET-AF</a>) and dabigatran (<a href="/detail/30/" rel="/short/30/">RE-LY</a>) may reduce stroke and/or bleeding</p><br />
			<p><red>Dronedarone</red> may be beneficial in low-risk paroxysmal or persistant AF patients (<a href="/detail/58/" rel="/short/58/">ATHENA</a>) but appears harmful in higher risk patients (<a href="/detail/38/" rel="/short/38/">PALLAS</a>)</p><br />
			<p><red>Ablation</red> appears successful in those failing rhythm control (<a href="/detail/46/" rel="/short/46/">APAF</a>, <a href="/detail/47/" rel="/short/47/">ThermoCool-AF</a>) but is not successful as a first-line treatment (<a href="/detail/94/" rel="/short/94/">MANTRA-PAF</a>)</p>
			</td>
		</tr>
		<tr>
			<th>Topic</th>
			<th>Therapy group</th>
			<th>Therapy</th>
			<th>Trial</th>
		</tr>
		<tr>
		{% for topic in topics_list|dictsort:"name" %}
			<td colspan="1" rowspan="{% get_topic_rows topic %}"><a href="#" name="{{ topic }}">{{ topic.displayname }}</a></td>
			{% for therapy in topic.therapy_set.all|dictsort:"name" %}
				<td colspan="1" rowspan="{% get_therapy_rows therapy %}">{{ therapy.displayname }}</td>
				{% for intervention in therapy.intervention_set.all|dictsort:"name" %}
				<td>{{intervention.displayname }}</td>
					<td>{% for trial in intervention.trial_set.all|dictsort:"date" %}
						<a href="/detail/{{ trial.id }}/" rel="/short/{{ trial.id }}/">{{ trial }}{% if not forloop.last %},{% endif %}</a>{% endfor %}
					</td>
		</tr>
				{% endfor %}
			{% endfor %}
		{% endfor %}
	</table>
		
</div>
{% endblock %}

cardiologytrials.org/django_cardiologytrials/templates/trialsapp/cad.html
{% extends "trialsapp/base.html" %}

{% block title %}Coronary artery disease (CAD) trials - CardiologyTrials.org{% endblock %}

{% block content %}
{% load trialsapp_extras %}
<div id="container">	
	<table class="trialtable">
		<tr>
			<th colspan="4"><h1>Evidence for CAD (coronary artery disease) therapies</h1></th>
		</tr>
		<tr>
			<td colspan="4">
			<p>The framingham heart study has identified <red>hypertension</red> as a risk factor for cornary artery disease and ace inhibitors and angiotensin receptor blockers may provide further benefit above BP reduction (<a href="/detail/71/" rel="/short/71/">HOPE</a>, <a href="/detail/72/" rel="/short/72/">ONTARGET</a>), though this is controversial (<a href="/detail/84/" rel="/short/84/">VALUE</a>).</p><br />
			<p><red>Statins</red> reduce mortality (<a href="/detail/1/" rel="/short/1/">4S</a>).</p><br />
			<p>Whilst <red>coronary artery bypass grafting</red> appears to reduce mortality in patients in high-risk diabetics (<a href="/detail/64/" rel="/short/64/">BARI-2D</a>, <a href="/detail/97/" rel="/short/97/">FREEDOM</a>) and patients with multi-vessel or left main stem disease (<a href="/detail/73/" rel="/short/73/">ASCERT</a>, <a href="/detail/63/" rel="/short/63/">SYNTAX</a>), <red>percutaneous coronary intervention</red> is much more controversial; <a href="/detail/74/" rel="/short/74/">COURAGE</a> showed no benefit for PCI over medical therapy, though <a href="/detail/93/" rel="/short/93/">FAME-2</a> may have shown some benefit.</p>
			</td>
		</tr>
		<tr>
			<th>Topic</th>
			<th>Therapy group</th>
			<th>Therapy</th>
			<th>Trial</th>
		</tr>
		<tr>
		{% for topic in topics_list|dictsort:"name" %}
			<td colspan="1" rowspan="{% get_topic_rows topic %}"><a href="#" name="{{ topic }}">{{ topic.displayname }}</a></td>
			{% for therapy in topic.therapy_set.all|dictsort:"name" %}
				<td colspan="1" rowspan="{% get_therapy_rows therapy %}">{{ therapy.displayname }}</td>
				{% for intervention in therapy.intervention_set.all|dictsort:"name" %}
				<td>{{intervention.displayname }}</td>
					<td>{% for trial in intervention.trial_set.all|dictsort:"date" %}
						<a href="/detail/{{ trial.id }}/" rel="/short/{{ trial.id }}/">{{ trial }}{% if not forloop.last %},{% endif %}</a>{% endfor %}
					</td>
		</tr>
				{% endfor %}
			{% endfor %}
		{% endfor %}
	</table>
		
</div>
{% endblock %}

cardiologytrials.org/django_cardiologytrials/templates/trialsapp/cardio.html
{% extends "trialsapp/base.html" %}

{% block title %}CardiologyTrials.org - Improving evidence-based medicine{% endblock %}

{% block content %}
{% load trialsapp_extras %}
<div id="container">	
	<table class="trialtable">
		<tr>
			<th colspan="4"><h1>Key cardiology trials in evidence based medicine - click on a trial for more information or a topic above for a summary</h1></th>
		</tr>
		<tr>
			<th>Topic</th>
			<th>Therapy group</th>
			<th>Therapy</th>
			<th>Trial</th>
		</tr>
		<tr>
		{% for topic in topics_list|dictsort:"name" %}
			<td colspan="1" rowspan="{% get_topic_rows topic %}"><a href="/{{ topic|lower }}/" name="{{ topic }}">{{ topic.displayname }}</a></td>
			{% for therapy in topic.therapy_set.all|dictsort:"name" %}
				<td colspan="1" rowspan="{% get_therapy_rows therapy %}">{{ therapy.displayname }}</td>
				{% for intervention in therapy.intervention_set.all|dictsort:"name" %}
				<td>{{intervention.displayname }}</td>
					<td>{% for trial in intervention.trial_set.all|dictsort:"date" %}
						<a href="/detail/{{ trial.id }}/" rel="/short/{{ trial.id }}/">{{ trial }}{% if not forloop.last %},{% endif %}</a>{% endfor %}
					</td>
		</tr>
				{% endfor %}
			{% endfor %}
		{% endfor %}
	</table>
		
</div>
{% endblock %}

cardiologytrials.org/django_cardiologytrials/templates/trialsapp/hf.html
{% extends "trialsapp/base.html" %}

{% block title %}Heart failure trials - CardiologyTrials.org{% endblock %}

{% block content %}
{% load trialsapp_extras %}
<div id="container">	
	<table class="trialtable">
		<tr>
			<th colspan="4"><h1>Evidence for heart failure therapies</h1></th>
		</tr>
		<tr>
			<td colspan="4">
			<p><red>ACE inhibitors</red> improve symptoms in CCF (<a href="/detail/3/" rel="/short/3/">CONSENSUS</a>) and reduce mortality even in asymptomatic patients with low ejection fraction (<a href="/detail/4/" rel="/short/4/">SOLVD</a>). <red>Angiotensin receptor blockers</red> also appear to share these benefits (<a href="/detail/7/" rel="/short/7/">CHARM</a>, <a href="/detail/8/" rel="/short/8/">ValHEFT</a>), though any benefit when added to ACEi is controversial (<a href="/detail/7/" rel="/short/7/">CHARM</a>, <a href="/detail/8/" rel="/short/8/">ValHEFT</a>).</p><br />
			<p><red>Aldosterone antagonists</red> do confer extra benefit when added to ACEi/ARBs in NYHA 3 (<a href="/detail/54/" rel="/short/54/">RALES</a>) and NYHA 2 CCF (<a href="/detail/56/" rel="/short/56/">EMPHASIS-HF</a>).</p><br />
			<p><red>Beta-blockers</red> also improve mortality and reduce hospitalisations (<a href="/detail/5/" rel="/short/5/">CIBIS-II</a>) with some evidence of superiority between agents (<a href="/detail/9/" rel="/short/9/">COMET</a>). If blockers such as <red>Ivabradine</red> is an alternative rate-controlling agent that appears beneficial in some patients (<a href="/detail/34/" rel="/short/34/">BEAUTIFUL</a>, <a href="/detail/57/" rel="/short/57/">SHIFT</a>).</p><br />
			<p>Neither routine anticoagulation with <red>warfarin</red> (<a href="/detail/85/" rel="/short/85/">WARCEF</a>) nor treatment with <red>digoxin</red> (<a href="/detail/67/" rel="/short/67/">DIG</a>) appear beneficial on mortality</p><br />
			<p>Insertion of <red>cardiac resynchronisation devices</red> (CRT) adds further benefit (<a href="/detail/32/" rel="/short/32/">MADIT-CRT</a>) above the benefits of inserting an implantable cardiac defibrillatory (ICD) (<a href="/detail/33/" rel="/short/33/">SCD-HeFT</a>).</p><br />
			<p><red>Statins</red> do not add benefit in CCF in patients with no other indication (<a href="/detail/80/" rel="/short/80/">CORONA</a>) and <red>ultrafiltration</red> appears inferior to stepped medical therapy in patients with acute cardio-renal syndrome</p><br />
			<p><red>Surgical revascularisation</red> may be beneficial in some patients (<a href="/detail/59/" rel="/short/59/">STITCH</a>) but the high crossover in this trial makes interpretation very difficult.</p>
			</td>
		</tr>
		<tr>
			<th>Topic</th>
			<th>Therapy group</th>
			<th>Therapy</th>
			<th>Trial</th>
		</tr>
		<tr>
		{% for topic in topics_list|dictsort:"name" %}
			<td colspan="1" rowspan="{% get_topic_rows topic %}"><a href="#" name="{{ topic }}">{{ topic.displayname }}</a></td>
			{% for therapy in topic.therapy_set.all|dictsort:"name" %}
				<td colspan="1" rowspan="{% get_therapy_rows therapy %}">{{ therapy.displayname }}</td>
				{% for intervention in therapy.intervention_set.all|dictsort:"name" %}
				<td>{{intervention.displayname }}</td>
					<td>{% for trial in intervention.trial_set.all|dictsort:"date" %}
						<a href="/detail/{{ trial.id }}/" rel="/short/{{ trial.id }}/">{{ trial }}{% if not forloop.last %},{% endif %}</a>{% endfor %}
					</td>
		</tr>
				{% endfor %}
			{% endfor %}
		{% endfor %}
	</table>
		
</div>
{% endblock %}

cardiologytrials.org/django_cardiologytrials/templates/trialsapp/htn.html
{% extends "trialsapp/base.html" %}

{% block title %}Hypertension trials - CardiologyTrials.org{% endblock %}

{% block content %}
{% load trialsapp_extras %}
<div id="container">	
	<table class="trialtable">
		<tr>
			<th colspan="4"><h1>Evidence for hypertension therapies</h1></th>
		</tr>
		<tr>
			<td colspan="4">
			<p>Pharmacological therapy for hypertension has been shown to reduce mortality, and many trials use stroke as an outcome. Most patients require multiple agents for good control (<a href="/detail/86/" rel="/short/86/">ALLHAT</a>)</p><br />
			<p><red>ACE inhibitors</red> (ACEi) seem to reduce stroke in patients 'not classically' hypertensive (<a href="/detail/16/" rel="/short/16/">PROGRESS</a>) and <red>angiotensin receptor blockers</red> (ARB) appear superior to beta-blockers for reducing mortality, even with similar blood pressure reductions (<a href="/detail/17/" rel="/short/17/">LIFE</a>).</p><br />
			<p><red>Calcium channel blockers</red> (CCB) may give better control than angiotensin receptor blockers (<a href="/detail/84/" rel="/short/84/">VALUE</a>) though this could be off-set by a class benefit from ARBs. May be the agent of choice when adding to an ACEi in high risk patients (<a href="/detail/102/" rel="/short/102/">ACCOMPLISH</a>)</p><br />
			<p><red>Thiazides</red> seem to give particularly good blood pressure control (<a href="/detail/86/" rel="/short/86/">ALLHAT</a>) though end-points were similar for <red>ACEi</red> and <red>CCB</red>. Also, when added as a second agent to an ACEi, a calcium channel blocker may be a better choice (<a href="/detail/102/" rel="/short/102/">ACCOMPLISH</a>)</p><br />
			<p><red>Alpha-blockers</red> appear less attractive and in <a href="/detail/86/" rel="/short/86/">ALLHAT</a> this arm was stopped early for increased cardiovascular events and heart failure</p><br />
			<p><red>Renal denervation</red> offers substantial blood pressure reductions in patients with resistant hypertension (<a href="/detail/98/" rel="/short/98/">Symplicity HTN-2</a>) but blinded trials have not yet been performed.</p>
			</td>
		</tr>
		<tr>
			<th>Topic</th>
			<th>Therapy group</th>
			<th>Therapy</th>
			<th>Trial</th>
		</tr>
		<tr>
		{% for topic in topics_list|dictsort:"name" %}
			<td colspan="1" rowspan="{% get_topic_rows topic %}"><a href="#" name="{{ topic }}">{{ topic.displayname }}</a></td>
			{% for therapy in topic.therapy_set.all|dictsort:"name" %}
				<td colspan="1" rowspan="{% get_therapy_rows therapy %}">{{ therapy.displayname }}</td>
				{% for intervention in therapy.intervention_set.all|dictsort:"name" %}
				<td>{{intervention.displayname }}</td>
					<td>{% for trial in intervention.trial_set.all|dictsort:"date" %}
						<a href="/detail/{{ trial.id }}/" rel="/short/{{ trial.id }}/">{{ trial }}{% if not forloop.last %},{% endif %}</a>{% endfor %}
					</td>
		</tr>
				{% endfor %}
			{% endfor %}
		{% endfor %}
	</table>
		
</div>
{% endblock %}

cardiologytrials.org/django_cardiologytrials/templates/trialsapp/surgery.html
{% extends "trialsapp/base.html" %}

{% block title %}Cardiac surgery trials - CardiologyTrials.org{% endblock %}

{% block content %}
{% load trialsapp_extras %}
<div id="container">	
	<table class="trialtable">
		<tr>
			<th colspan="4"><h1>Evidence for cardiac surgery</h1></th>
		</tr>
		<tr>
			<td colspan="4">
			<p>Coming soon</p>
			</td>
		</tr>
		<tr>
			<th>Topic</th>
			<th>Therapy group</th>
			<th>Therapy</th>
			<th>Trial</th>
		</tr>
		<tr>
		{% for topic in topics_list|dictsort:"name" %}
			<td colspan="1" rowspan="{% get_topic_rows topic %}"><a href="#" name="{{ topic }}">{{ topic.displayname }}</a></td>
			{% for therapy in topic.therapy_set.all|dictsort:"name" %}
				<td colspan="1" rowspan="{% get_therapy_rows therapy %}">{{ therapy.displayname }}</td>
				{% for intervention in therapy.intervention_set.all|dictsort:"name" %}
				<td>{{intervention.displayname }}</td>
					<td>{% for trial in intervention.trial_set.all|dictsort:"date" %}
						<a href="/detail/{{ trial.id }}/" rel="/short/{{ trial.id }}/">{{ trial }}{% if not forloop.last %},{% endif %}</a>{% endfor %}
					</td>
		</tr>
				{% endfor %}
			{% endfor %}
		{% endfor %}
	</table>
		
</div>
{% endblock %}